openapi: 3.1.0
info:
  title: FastAPI
  version: 0.1.0
paths:
  /services/:
    post:
      summary: Create Service
      operationId: create_service_services__post
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
        required: true
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
  /services/{service_id}:
    get:
      summary: Read Service
      operationId: read_service_services__service_id__get
      parameters:
      - name: service_id
        in: path
        required: true
        schema:
          type: string
          title: Service Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    put:
      summary: Update Service
      operationId: update_service_services__service_id__put
      parameters:
      - name: service_id
        in: path
        required: true
        schema:
          type: string
          title: Service Id
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Service'
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
    delete:
      summary: Delete Service
      operationId: delete_service_services__service_id__delete
      parameters:
      - name: service_id
        in: path
        required: true
        schema:
          type: string
          title: Service Id
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema: {}
        '422':
          description: Validation Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HTTPValidationError'
components:
  schemas:
    HTTPValidationError:
      properties:
        detail:
          items:
            $ref: '#/components/schemas/ValidationError'
          type: array
          title: Detail
      type: object
      title: HTTPValidationError
    Service:
      properties:
        title:
          type: string
          title: Title
        description:
          type: string
          title: Text
        creator_id:
          type: integer
          title: Creator Id
      type: object
      required:
      - title
      - description
      - creator_id
      title: Service
    ValidationError:
      properties:
        loc:
          items:
            anyOf:
            - type: string
            - type: integer
          type: array
          title: Location
        msg:
          type: string
          title: Message
        type:
          type: string
          title: Error Type
      type: object
      required:
      - loc
      - msg
      - type
      title: ValidationError
